[package]
name = "rusty-chain"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.97"
hash = "0.3.0"
hex = "0.4.3"
hex-literal = "1.0.0"
sha2 = "0.10.8"
